# Generated by Django 5.2 on 2025-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Requested', 'Đã yêu cầu'), ('Confirmed', 'Đã xác nhận'), ('Completed', 'Đã hoàn thành'), ('CanceledByPatient', 'Đã hủy bởi bệnh nhân'), ('CanceledByDoctor', 'Đã hủy bởi bác sĩ')], default='Requested', max_length=30),
        ),
    ]
