# Generated by Django 5.1.6 on 2025-05-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(choices=[('ND', 'Nội khoa'), ('NK', 'Nhi khoa'), ('TM', 'Tim mạch'), ('DL', 'Da liễu'), ('DK', 'Đa khoa'), ('CT', 'Chấn thương chỉnh hình'), ('TT', 'Tâm thần'), ('TK', 'Thần kinh')], max_length=2)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
